# Name of the project
PROJECT_NAME = Clinic Management System

# Output directory
BUILD = build

# All source code files
SRC = project_main.c\
src/clinic main.c
OBJ = clinic main.o
INC = inc
CFLAGS = I$(INC)
a.out:$(OBJ)
   gcc $ -I$(INC)-o $@
%.o:src%
   gcc $^ -I$(INC)-c
run : target
   ./all.out
clear:
   rm all.out *.o src/*.o
   
