name: C/C++ CI - Build Status

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: gcc 3_Implementation.c -o 3_Implementation.exe
    - name: Run
      run: .\3_Implementation.exe

